import Head from "next/head";
import React from "react";
import Chat from "./Chat";
import Header from "./Header";

function Layout({ children, pageTitle }) {
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
    </>
  );
}

export default Layout;
