import Head from "next/head";
import React from "react";
import Chat from "./Chat";
import Header from "./Header";

function Layout({ children, pageTitle }) {
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta
          name="Pierre's awesome portfolio"
          content="Generated by me, myself and I"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
}

export default Layout;
